name: Flutter Web Deploy

on:
  push:
    # سيتم تفعيل البناء عند الرفع على أي فرع (مشروع) جديد
    branches:
      - '**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Web and Initialize Project
        run: |
          flutter config --enable-web
          # الحل النهائي: إجبار فلاتر على استخدام اسم حزمة صالح (app) 
          # هذا يمنع الخطأ الناتج عن وجود شرطات (-) في اسم المستودع الرئيسي
          if [ ! -d "web" ]; then
            flutter create . --project-name=app --platforms web
          fi

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        # ضبط مسار المعاينة ليكون متوافقاً مع المجلد الفرعي في GitHub Pages
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/${{ github.ref_name }}/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          # رفع ملفات الويب الناتجة إلى مجلد يحمل اسم الفرع (المشروع) الحالي
          destination_dir: ${{ github.ref_name }}
          # الحفاظ على المشاريع (الفروع) الأخرى المنشورة مسبقاً
          keep_files: true
